name: CD com GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIASQ5WMQMZYHTDPETZ
          aws-secret-access-key: 5WtTwRMNqjTgyPqIDR6egfG6XsyRIjxWe2rEY600
          aws-session-token: IQoJb3JpZ2luX2VjEPv//////////wEaCXVzLXdlc3QtMiJIMEYCIQDSJU2HgnlLYT7mtx3EYAcPo8sxntuTrrt6hEyfo/xEgwIhAPEEcgqBfjI30unVdIc+mWGCzOiCiAjGDMQ4jkLILZOJKrgCCGQQABoMMTczNzkxODA2MjU5IgwMax1LMceH00z4xYYqlQLjrDApLdErV5o6K1j0T5VrM3PHPF4w2/CShNFm4FKOLYUnmc8xoWP38Ofu9IdFBRvSmylkNKnQdzkUhAkC3EQoHDG51rYJpoUyulJXtJvAN7dgQn2H6XOSalav4QXPi5CXwyjFGEwvufsbY5cxMhpL+q/0qzgsLfbGQThi1rTi6FGNI3pz2h+97DqcHsGKt1wNv5QUIwljLUZ0/CilAx1dl86hiXUPd701FPP124CMqzPTJsc7FFgTF4IDhea9Krh5L4xPndC3aE/Xerzyj2VxPt/Hx/sp0ZLswV1wxTfgkVacUtX+MIsNBOzKnbGFhFn+i6xQ1bMZb1OaltnxmyikZ7gDg+VSmV4NPM9mAYApEV5y+8eWMKTF58UGOpwBUMbbg1Da13vmhBXk4laMtWlTny/oW5RBDi8cRxvrI3UNUFQSSbM84NaZ27H6eQ7Lzd2gIrswh0Dv38wHkFsWt13ynSaV0oWVnQJgvNJWs0fdYAKevlA3ZJ7MRVef8WxtnE2+DviIQGQ4AOFC2/3bCnOZbLzuZ3SOvB54LP2cF6oRmwID+ieqNvFC7d5GCV6mGDnI25K+ypZoyfpq
          aws-region: us-east-1

      - name: ECR login
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 173791806259.dkr.ecr.us-east-1.amazonaws.com

      - name: Build e Push da imagem Docker
        run: |
          docker build -t hello-flask .
          docker tag hello-flask:latest 173791806259.dkr.ecr.us-east-1.amazonaws.com/hello-flask:latest
          docker push 173791806259.dkr.ecr.us-east-1.amazonaws.com/hello-flask:latest
