name: CI com GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform_validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Inicializar Terraform
        run: terraform init -backend=false
        working-directory: infraestrutura

      - name: Validar sintaxe do Terraform
        run: terraform validate
        working-directory: infraestrutura
